spring:
    application:
        name: product-api-jwt
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/product-api
    datasource:
        url: jdbc:postgresql://localhost:5432/productdb
        username: superuser
        password: superpass
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
